services:
  db:
    image: postgres:15.3
    volumes:
      - "/db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: cs3j73
      POSTGRES_USER: random1
      POSTGRES_DB: horizon
    ports:
      - "5432:5432"